config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resource :pictures, only: [:create]
  end
end

app/models/spree/picture.rb
module Spree
  class Picture < ActiveRecord::Base
    has_attached_file :image
    validates_attachment_content_type :image, :presence => true,
      :content_type => /\Aimage\/.*\Z/,
      :size => { :in => 0..10.megabytes }
  end
end

app/controllers/spree/admin/pictures_controller.rb
module Spree
  module Admin
    class PicturesController < ApplicationController
      def create
        @picture = Picture.new(picture_params)
        if @picture.save
          render json: {success: true, file_path: @picture.image.url}
        else
          render json: {success: false, msg: @picture.errors.full_messages}
        end
      end

      private

      def picture_params
        params.require(:picture).permit(:image)
      end
    end
  end
end

app/views/shared/_simditor.html.erb
<script>
  $(function() {
    var editor = new Simditor({
      textarea: $('#product_description'),
      upload: {'url': "<%= admin_pictures_url %>", 'fileKey': 'picture[image]'},
      pasteImage: true,
      defaultImage: '<%= image_path "upload-loading.png" %>',
      toolbar: [
        'title',
        'bold',
        'italic',
        'underline',
        'strikethrough',
        'fontScale',
        'color',
        'ol',
        'ul',
        'blockquote',
        'table',
        'link',
        'image',
        'hr',
        'indent',
        'outdent',
        'alignment',
        'fullscreen',
        'html'
      ]
    });
  });
</script>